---
language: python
python: "2.7"

env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y curl python-pip python-apt gcc

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - printf '[defaults]\nroles_path = ./roles' > ansible.cfg

script:
  # Check the role/playbook's syntax.

  - ansible-playbook -i roles/logstash-forwarder/tests/inventory roles/logstash-forwarder/tests/$SITE --syntax-check

  # Run the role/playbook with ansible-playbook.
  - ansible-playbook -i roles/logstash-forwarder/tests/inventory roles/logstash-forwarder/tests/$SITE --connection=local --sudo

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i roles/logstash-forwarder/tests/inventory roles/logstash-forwarder/tests/$SITE --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Make sure Java is installed.
  - >
    which java
    && (echo 'Java is installed: pass' && exit 0)
    || (echo 'Java is installed: fail' && exit 1)

  # Make sure Kibana is accessible
  - >
    ps aux
    | grep log
    | awk -F" " '{print $11}' 
    | grep -q /opt/logstash-forwarder/bin/logstash-forwarder
    && (echo 'Logstash-forwarder is running: pass' && exit 0)
    || (echo 'Logstash-forwarder is running: fail' && exit 1)
